# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    ensure_git_status_clean

    badge

    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "adhoc",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: true)
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "adhoc",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: true)

    gym(scheme: "Whereabouts",
      output_directory: "./build", 
      clean: true)

    pilot(changelog: File.exist?('metadata/beta-changelog.txt') ? File.read('metadata/beta-changelog.txt') : '', distribute_external: false, wait_processing_interval: 120)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "appstore",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: true)

    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "appstore",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: true)
    # snapshot

    gym(scheme: "Whereabouts") # Build your app - more options available
    deliver(force: true)

    # frameit
  end

  desc "Creates all profiles if nessacary"
  lane :match do
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "development",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: false)
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "development",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: false)

    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "adhoc",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: false)
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "adhoc",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: false)

    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "appstore",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: false)
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "appstore",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: false)
  end

  desc "Make sure that Xcode doesn't break everything"
  lane :xcode do
    install_xcode_plugin(
      url: "https://github.com/fastlane/FixCode/releases/download/0.5.0/FixCode.xcplugin.zip"
    )
  end

end

after_all do |lane|
  notification(subtitle:"fastlane finished '#{lane}'") # Mac OS X Notification
end