# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "adhoc",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: true)

    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "adhoc",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: true)

    sigh(force: true)

    gym(scheme: "Whereabouts",
      output_directory: "./build", 
      clean: true)

    pilot(distribute_external: false)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "appstore",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: true)

    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "appstore",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: true)
    # snapshot

    gym(scheme: "Whereabouts") # Build your app - more options available
    deliver(force: true)

    # frameit
  end

  desc "Creates all profiles if nessacary"
  lane :match do
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "development",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: false)
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "development",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: false)

    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "adhoc",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: false)
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "adhoc",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: false)

    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "appstore",
      app_identifier: "net.naturaln0va.Whereabouts",
      readonly: false)
    match(git_url: "https://github.com/naturaln0va/certificates.git",
      type: "appstore",
      app_identifier: "net.naturaln0va.Whereabouts.Quick-Location",
      readonly: false)
  end

  desc "Make sure that XCode doesn't break everything"
  lane :xcode do
    install_xcode_plugin(
      url: "https://github.com/fastlane/FixCode/releases/download/0.5.0/FixCode.xcplugin.zip"
    )
  end

  desc "Adds icon badging to the app"
  lane :badge do

  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
